# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
AllCops:
  TargetRubyVersion: 3.3
  Exclude:
    - 'bin/*'
    - 'vendor/*'

Layout/LineLength:
  Max: 150


Style/StringLiterals:
  EnforcedStyle: double_quotes
