version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: breerop
      POSTGRES_PASSWORD: breerop
      POSTGRES_DB: my_project_development
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - ".:/my_project"
    ports:
      - "3000:3000"
    depends_on:
      - db
