default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: breerop
  password: breerop
  host: localhost
  port: 3306

development:
  <<: *default
  database: my_portfolio_project_development

test:
  <<: *default
  database: my_portfolio_project_test

production:
  <<: *default
  database: my_portfolio_project_production
  username: <%= ENV['DB_USERNAME'] %> # Use environment variable for production
  password: <%= ENV['DB_PASSWORD'] %> # Use environment variable for production
  host: <%= ENV['DB_HOST'] || 'localhost' %> # Use environment variable for production
