development:
  adapter: postgresql
  encoding: unicode
  database: my_portfolio_project_development
  pool: 5
  username: breerop
  password: breerop
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: my_portfolio_project_test
  pool: 5
  username: breerop
  password: breerop
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: my_portfolio_project_production
  pool: 5
  username: breerop
  password: breerop
  host: localhost
